--------------------------------------------------------------------------------
-- FGaussian - Szenenablage im Schema DEMO (PDBORCL, Oracle 21c)
--
-- Eine Szene ist eine Kopfzeile plus wenige grosse Bloecke. Splats einzeln als
-- Zeilen abzulegen waere bei sechsstelligen Zahlen ein Ladezeitproblem; ein BLOB
-- je Attributblock laedt in einem Rutsch und passt genau zum float[]-Layout im
-- Speicher (siehe com.dan.fgaussian.core.FSplatCodec).
--
-- Koordinaten liegen in SRID 25832 (ETRS89 / UTM 32N, Meter). Die Splats selbst
-- sind auf den Szenenursprung bezogen; CENTRE_EAST/CENTRE_NORTH halten fest, wo
-- dieser Ursprung in UTM liegt. Damit bleibt die Szene georeferenziert, ohne
-- dass in float mit Hochwerten um 5 984 000 gerechnet werden muss.
--
-- Aufruf:  sqlplus DEMO/<pwd>@//localhost:1521/PDBORCL @fgs_schema.sql
--------------------------------------------------------------------------------

-- Vorhandene Objekte entfernen (Reihenfolge wegen der Fremdschluessel).
BEGIN
  FOR t IN (SELECT table_name FROM user_tables
             WHERE table_name IN ('FGS_ANCHOR','FGS_BLOCK','FGS_SCENE')
             ORDER BY DECODE(table_name,'FGS_ANCHOR',1,'FGS_BLOCK',2,3))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

DELETE FROM user_sdo_geom_metadata
 WHERE table_name IN ('FGS_SCENE','FGS_ANCHOR');
COMMIT;

--------------------------------------------------------------------------------
-- Kopfzeile der Szene
--------------------------------------------------------------------------------
CREATE TABLE FGS_SCENE (
  ID            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  NAME          VARCHAR2(128)       NOT NULL,
  SRID          NUMBER(10)          DEFAULT 25832      NOT NULL,
  SPLAT_COUNT   NUMBER(12)          DEFAULT 0          NOT NULL,
  SOURCE_KIND   VARCHAR2(16)        DEFAULT 'XYZ'      NOT NULL,
  EXAGGERATION  BINARY_FLOAT        DEFAULT 1          NOT NULL,
  CENTRE_EAST   NUMBER,
  CENTRE_NORTH  NUMBER,
  SH_DEGREE     NUMBER(1)           DEFAULT 0          NOT NULL,
  BBOX          SDO_GEOMETRY,
  NOTE          VARCHAR2(2000),
  CREATED       TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FGS_SCENE_PK PRIMARY KEY (ID),
  CONSTRAINT FGS_SCENE_UK UNIQUE (NAME),
  CONSTRAINT FGS_SCENE_KIND_CK CHECK (SOURCE_KIND IN ('XYZ','PLY','SDO','MIX')),
  CONSTRAINT FGS_SCENE_SH_CK   CHECK (SH_DEGREE BETWEEN 0 AND 3)
);

COMMENT ON TABLE  FGS_SCENE                IS 'Gauss-Splat-Szene, Kopfdaten';
COMMENT ON COLUMN FGS_SCENE.SOURCE_KIND    IS 'XYZ=Hoehenraster, PLY=3DGS-Rekonstruktion, SDO=Oracle Spatial, MIX=zusammengesetzt';
COMMENT ON COLUMN FGS_SCENE.EXAGGERATION   IS 'Hoehenueberhoehung, mit der die Szene gebaut wurde';
COMMENT ON COLUMN FGS_SCENE.CENTRE_EAST    IS 'Rechtswert des Szenenursprungs in SRID';
COMMENT ON COLUMN FGS_SCENE.CENTRE_NORTH   IS 'Hochwert des Szenenursprungs in SRID';
COMMENT ON COLUMN FGS_SCENE.SH_DEGREE      IS '0 = Farbe steckt im COL-Block, 1..3 = zusaetzlicher SH-Block';

--------------------------------------------------------------------------------
-- Attributbloecke
--
-- SEQ erlaubt spaeter, sehr grosse Szenen in mehrere BLOBs zu stueckeln; heute
-- schreibt das DAO je Art genau einen Block mit SEQ = 0.
--------------------------------------------------------------------------------
CREATE TABLE FGS_BLOCK (
  SCENE_ID      NUMBER              NOT NULL,
  KIND          VARCHAR2(8)         NOT NULL,
  SEQ           NUMBER(6)           DEFAULT 0 NOT NULL,
  SPLAT_COUNT   NUMBER(12)          NOT NULL,
  DATA          BLOB                NOT NULL,
  CONSTRAINT FGS_BLOCK_PK PRIMARY KEY (SCENE_ID, KIND, SEQ),
  CONSTRAINT FGS_BLOCK_FK FOREIGN KEY (SCENE_ID)
      REFERENCES FGS_SCENE (ID) ON DELETE CASCADE,
  CONSTRAINT FGS_BLOCK_KIND_CK CHECK (KIND IN ('POS','SCALE','ROT','COL','SH'))
) LOB (DATA) STORE AS SECUREFILE FGS_BLOCK_LOB (
    ENABLE STORAGE IN ROW CHUNK 8192 NOCACHE LOGGING
);

COMMENT ON TABLE  FGS_BLOCK            IS 'Splat-Attribute als float32-Bloecke, Little Endian';
COMMENT ON COLUMN FGS_BLOCK.KIND       IS 'POS(3), SCALE(3), ROT(4), COL(4: r,g,b,a), SH(variabel)';
COMMENT ON COLUMN FGS_BLOCK.SPLAT_COUNT IS 'Splats in diesem Block, zur Laengenpruefung beim Lesen';

-- Hinweis: SECUREFILE-Kompression (COMPRESS MEDIUM) wuerde die Bloecke deutlich
-- verkleinern, setzt aber die Advanced Compression Option voraus und ist hier
-- deshalb bewusst nicht gesetzt.

--------------------------------------------------------------------------------
-- Ankerpunkte: benannte Orte in der Szene (Molenkopf, Kaikante, POI)
--------------------------------------------------------------------------------
CREATE TABLE FGS_ANCHOR (
  ID            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  SCENE_ID      NUMBER              NOT NULL,
  LABEL         VARCHAR2(256),
  KIND          VARCHAR2(32),
  PALETTE_ID    NUMBER,
  GEOM          SDO_GEOMETRY,
  CONSTRAINT FGS_ANCHOR_PK PRIMARY KEY (ID),
  CONSTRAINT FGS_ANCHOR_FK FOREIGN KEY (SCENE_ID)
      REFERENCES FGS_SCENE (ID) ON DELETE CASCADE
);

COMMENT ON COLUMN FGS_ANCHOR.PALETTE_ID IS 'Verweis auf COLOR_ADMIN, falls der Anker eine Palette traegt';

CREATE INDEX FGS_ANCHOR_SCENE_IX ON FGS_ANCHOR (SCENE_ID);

--------------------------------------------------------------------------------
-- Raeumliche Metadaten und Indizes
--
-- Der Bereich deckt Schleswig-Holstein in UTM 32N grosszuegig ab; die Toleranz
-- von 0,005 m ist fuer Hoehenraster mit 5 m Zellweite reichlich fein.
--------------------------------------------------------------------------------
INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
VALUES ('FGS_SCENE', 'BBOX',
        SDO_DIM_ARRAY(
          SDO_DIM_ELEMENT('X',  200000,  900000, 0.005),
          SDO_DIM_ELEMENT('Y', 5200000, 6200000, 0.005)),
        25832);

INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
VALUES ('FGS_ANCHOR', 'GEOM',
        SDO_DIM_ARRAY(
          SDO_DIM_ELEMENT('X',  200000,  900000, 0.005),
          SDO_DIM_ELEMENT('Y', 5200000, 6200000, 0.005)),
        25832);
COMMIT;

CREATE INDEX FGS_SCENE_BBOX_SX  ON FGS_SCENE  (BBOX) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;
CREATE INDEX FGS_ANCHOR_GEOM_SX ON FGS_ANCHOR (GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

--------------------------------------------------------------------------------
-- Uebersicht: Szenen mit belegtem Speicher
--------------------------------------------------------------------------------
CREATE OR REPLACE VIEW FGS_SCENE_INFO AS
SELECT s.ID,
       s.NAME,
       s.SOURCE_KIND,
       s.SPLAT_COUNT,
       s.EXAGGERATION,
       ROUND(NVL(b.BYTES, 0) / 1048576, 2) AS MB,
       s.CREATED
  FROM FGS_SCENE s
  LEFT JOIN (SELECT SCENE_ID, SUM(DBMS_LOB.GETLENGTH(DATA)) AS BYTES
               FROM FGS_BLOCK
              GROUP BY SCENE_ID) b
    ON b.SCENE_ID = s.ID;

--------------------------------------------------------------------------------
-- Lesezugriff auf die Geodaten in OGP (dort als OGP oder als DBA ausfuehren):
--
--   GRANT SELECT ON OGP.HAFEN      TO DEMO;
--   GRANT SELECT ON OGP.STRAND     TO DEMO;
--   GRANT SELECT ON OGP.WALD       TO DEMO;
--   GRANT SELECT ON OGP.SEEN       TO DEMO;
--   GRANT SELECT ON OGP.PARKS      TO DEMO;
--   GRANT SELECT ON OGP.PARKPLATZ  TO DEMO;
--
-- ALL_SDO_GEOM_METADATA zeigt fremde Eintraege nur, wenn das Leserecht auf der
-- jeweiligen Tabelle besteht - ohne die Grants findet findGeometryColumn() die
-- Geometriespalte nicht.
--------------------------------------------------------------------------------

SELECT table_name FROM user_tables WHERE table_name LIKE 'FGS%' ORDER BY 1;
