--------------------------------------------------------------------------------
-- OGP.GEBAEUDE - Gebaeudeumringe fuer die Kachel Niendorfer Hafen
--
-- Das ist der letzte fehlende Datensatz: OGP enthaelt Gemeinden, Schutzgebiete,
-- Seen, Wald und die zwoelf POI-Tabellen, aber keine Gebaeude. Sobald diese
-- Tabelle gefuellt ist, stellt FExtrusionBuilder die Haeuser auf das Gelaende.
--
-- Als OGP ausfuehren.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1) Overpass-Abfrage
--
-- In Overpass Turbo ausfuehren und als GeoJSON exportieren. Der Ausschnitt ist
-- die DGM5-Kachel 618/5984 mit etwas Rand, in WGS 84:
--
--   [out:json][timeout:90];
--   (
--     way["building"](53.9905,10.7985,54.0055,10.8230);
--     relation["building"](53.9905,10.7985,54.0055,10.8230);
--   );
--   out geom;
--
-- Erwartungswert fuer Niendorf: einige hundert Gebaeude. Interessant sind die
-- Schluessel building, name, building:levels und height.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 2) Zieltabelle
--
-- HEIGHT_M ist die Bauhoehe, die FExtrusionBuilder verwendet. OSM liefert sie
-- selten direkt; ueblich ist die Geschosszahl. Die Umrechnung steht als
-- virtuelle Spalte in der Tabelle, damit sie nicht in jeder Abfrage wiederholt
-- werden muss: drei Meter je Geschoss, ersatzweise siebeneinhalb Meter.
--------------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE GEBAEUDE CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

DELETE FROM user_sdo_geom_metadata WHERE table_name = 'GEBAEUDE';
COMMIT;

CREATE TABLE GEBAEUDE (
  ID        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  OSM_ID    NUMBER,
  NAME      VARCHAR2(256),
  ART       VARCHAR2(64),          -- OSM-Wert von building=*
  LEVELS    NUMBER(4,1),           -- building:levels
  HEIGHT    NUMBER(6,2),           -- height, falls gesetzt
  HEIGHT_M  NUMBER GENERATED ALWAYS AS (
                NVL(HEIGHT, NVL(LEVELS, 0) * 3)
            ) VIRTUAL,
  GEOM      SDO_GEOMETRY,
  CONSTRAINT GEBAEUDE_PK PRIMARY KEY (ID)
);

COMMENT ON COLUMN GEBAEUDE.HEIGHT_M IS 'Bauhoehe in Metern; aus HEIGHT, sonst aus LEVELS x 3';

INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
VALUES ('GEBAEUDE', 'GEOM',
        SDO_DIM_ARRAY(
          SDO_DIM_ELEMENT('Longitude',  -180, 180, 0.0000005),
          SDO_DIM_ELEMENT('Latitude',    -90,  90, 0.0000005)),
        8307);
COMMIT;

CREATE INDEX GEBAEUDE_GEOM_SX ON GEBAEUDE (GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

--------------------------------------------------------------------------------
-- 3) Laden
--
-- Derselbe Weg wie bei den uebrigen OGP-Tabellen. Mit GDAL waere es etwa:
--
--   ogr2ogr -f OCI "OCI:OGP/ogp@//localhost:1521/PDBORCL" gebaeude.geojson ^
--           -nln GEBAEUDE -a_srs EPSG:4326 -lco SRID=8307 -lco GEOMETRY_NAME=GEOM ^
--           -lco DIM=2 -append
--
-- Wichtig ist nur das Ergebnis: Polygone in SRID 8307 in der Spalte GEOM,
-- Geschosszahl in LEVELS oder Hoehe in HEIGHT.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 4) Leserecht fuer die Szenenablage
--------------------------------------------------------------------------------
GRANT SELECT ON GEBAEUDE TO DEMO;

--------------------------------------------------------------------------------
-- 5) Pruefen
--
-- Der Ausschnitt ist hier in WGS 84 angegeben; FSdoPolygonSource rechnet
-- spaeter selbst um und fragt mit einem Fenster in UTM 32N.
--------------------------------------------------------------------------------
SELECT COUNT(*) AS GEBAEUDE_GESAMT FROM GEBAEUDE;

SELECT COUNT(*) AS IN_DER_KACHEL
  FROM GEBAEUDE g
 WHERE SDO_FILTER(g.GEOM,
         SDO_GEOMETRY(2003, 8307, NULL, SDO_ELEM_INFO_ARRAY(1,1003,3),
           SDO_ORDINATE_ARRAY(10.7985, 53.9905, 10.8230, 54.0055)),
         'querytype=WINDOW') = 'TRUE';

SELECT NVL(ART,'(ohne)') ART, COUNT(*) ANZAHL, ROUND(AVG(HEIGHT_M),1) MITTLERE_HOEHE
  FROM GEBAEUDE GROUP BY ART ORDER BY 2 DESC;

--------------------------------------------------------------------------------
-- 6) Danach in FGaussianOracleDemo die Ebene ergaenzen:
--
--   new Layer("OGP.GEBAEUDE", "HEIGHT_M", FLandCover.BUILDING, 7.5f)
--
-- Die Geometriespalte findet findGeometryColumn() selbst; HEIGHT_M wird je
-- Objekt gelesen, und wo sie 0 ist, greift die Voreinstellung von 7,5 m.
--------------------------------------------------------------------------------
